### ISSUE TITLE
license

### ISSUE THREAD

**Issue by benatkin** [insin/DOMBuilder#8]
I don't see a license in the README or package.json. Mind adding one?

**Comment by benatkin** [comment]
Ack. I forgot to run `ack`! It's MIT as per the JavaScript source. So now the issue is just that it would be nice if the license were also in README.md, package.json, and/or a root-level file named MIT-LICENSE or LICENSE. Also the full MIT license with the name(s) of the copyright holder is preferable.

**Comment by insin** [comment]
It's part of the docs, but I'll put the main bit in the README so it's clear
